[lucidboard]

"LucidboardWeb.Endpoint".http.port = 8080
"LucidboardWeb.Endpoint".url.port = 8080
"LucidboardWeb.Endpoint".url.host = "${URL_HOST | default: localhost}"

"Lucidboard.Repo".database = "${PG_DB | default: lucidboard_prod}"
"Lucidboard.Repo".hostname = "${PG_HOST | default: db}"
"Lucidboard.Repo".port = "${PG_PORT | default: 5432}"
"Lucidboard.Repo".password = "${PG_PASS | default: verysecure123}"

auth_provider = "pingfed"

[ueberauth."Ueberauth.Strategy.Github.OAuth"]
client_id = "${GITHUB_CLIENT_ID}"
client_secret = "${GITHUB_CLIENT_SECRET}"

[ueberauth."Ueberauth.Strategy.PingFed.OAuth"]
site = "${PINGFED_SITE}"
redirect_uri = "${PINGFED_REDIRECT_URI}"
client_id = "${PINGFED_CLIENT_ID}"
client_secret = "${PINGFED_CLIENT_SECRET}"
